<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\RewardItem;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB; // Added for DB raw statements

class RewardItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Temporarily disable foreign key checks for truncate
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        RewardItem::truncate();
        // It's also good practice to truncate the related table if you expect a clean slate
        // \App\Models\PointRedemption::truncate(); // Uncomment if you want to clear redemptions too
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');


        $rewards = [
            [
                'name' => 'RM10 Voucher',
                'description' => 'Get RM10 off your next purchase.',
                'points_cost' => 300,
                'image_url' => 'assets/promo/membership.jpg', // Assuming these paths are relative to frontend assets
                'is_active' => true,
                'quantity' => null, // Unlimited
            ],
            [
                'name' => 'RM20 Voucher',
                'description' => 'Get RM20 off your next purchase.',
                'points_cost' => 500,
                'image_url' => 'assets/promo/idk.jpg',
                'is_active' => true,
                'quantity' => 100, // Limited quantity
            ],
            [
                'name' => 'Car Wash Coupon',
                'description' => 'Free standard car wash.',
                'points_cost' => 150,
                'image_url' => 'assets/promo/promo2.jpg',
                'is_active' => true,
                'quantity' => null,
            ],
            [
                'name' => 'Free Battery Check',
                'description' => 'Complimentary battery health check service.',
                'points_cost' => 100,
                'image_url' => 'assets/promo/promo3.jpg',
                'is_active' => true,
                'quantity' => null,
            ],
            [
                'name' => 'Expired Test Reward',
                'description' => 'This reward was only valid last month.',
                'points_cost' => 50,
                'image_url' => null,
                'is_active' => true,
                'quantity' => null,
                'valid_until' => now()->subMonth(),
            ],
            [
                'name' => 'Inactive Test Reward',
                'description' => 'This reward is not active.',
                'points_cost' => 20,
                'image_url' => null,
                'is_active' => false,
                'quantity' => null,
            ]
        ];

        foreach ($rewards as $reward) {
            RewardItem::create([
                'id' => (string) Str::uuid(), // Ensure UUID is set if not auto-generated by model trait
                'name' => $reward['name'],
                'description' => $reward['description'],
                'points_cost' => $reward['points_cost'],
                'image_url' => $reward['image_url'],
                'is_active' => $reward['is_active'],
                'quantity' => $reward['quantity'],
                'valid_from' => $reward['valid_from'] ?? null,
                'valid_until' => $reward['valid_until'] ?? null,
            ]);
        }
    }
}
